// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct connection (port 5432) - for migrations/db push
    // MUST use DIRECT_URL, NOT DATABASE_URL (pooler doesn't support prepared statements)
    url: process.env["DIRECT_URL"],
  },
});
